# Site settings
title: Siddarth Sampangi
email: siddarthsampangi@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ssampang.github.io" # the base hostname & protocol for your site
github_username:  ssampang

# Build settings
markdown: kramdown
permalink: /:title
